#!/bin/bash
#
# Ralph Wiggum Exploratory Testing Loop
# ======================================
# Runs Claude Code in a loop to execute exploratory tests one at a time.
# Each iteration picks up where the last one left off via progress.txt
#
# Usage: ./run-exploratory-tests.sh [max_iterations]
#

set -e

# Configuration
PROJECT_DIR="/Users/johnmaher/development/meal-planner-demo"
TESTS_FILE="$PROJECT_DIR/exploratory-tests.json"
PROGRESS_FILE="$PROJECT_DIR/progress.txt"
PROMPT_FILE="$PROJECT_DIR/EXPLORATORY_PROMPT.md"
BUGS_FILE="$PROJECT_DIR/bugs-found.md"
MAX_ITERATIONS=${1:-42}  # Default to total test count, or pass as argument

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Ralph Wiggum Exploratory Testing Loop                      ║${NC}"
echo -e "${BLUE}║     meal-planner-demo Production Readiness                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    # Check if tests file exists
    if [ ! -f "$TESTS_FILE" ]; then
        echo -e "${RED}ERROR: Tests file not found: $TESTS_FILE${NC}"
        exit 1
    fi

    # Check if prompt file exists
    if [ ! -f "$PROMPT_FILE" ]; then
        echo -e "${RED}ERROR: Prompt file not found: $PROMPT_FILE${NC}"
        exit 1
    fi

    # Check if claude is available
    if ! command -v claude &> /dev/null; then
        echo -e "${RED}ERROR: 'claude' command not found. Install Claude Code CLI.${NC}"
        exit 1
    fi

    # Check if app is running
    if ! curl -s http://localhost:3000 > /dev/null 2>&1; then
        echo -e "${YELLOW}WARNING: App not responding at http://localhost:3000${NC}"
        echo -e "${YELLOW}Run './init.sh' first to start the development server${NC}"
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi

    echo -e "${GREEN}Prerequisites check passed${NC}"
}

# Initialize progress file if it doesn't exist
init_progress_file() {
    if [ ! -f "$PROGRESS_FILE" ]; then
        echo -e "${YELLOW}Initializing progress file...${NC}"
        cat > "$PROGRESS_FILE" << 'EOF'
################################################################################
#                     EXPLORATORY TESTING PROGRESS LOG                         #
#                         meal-planner-demo                                    #
################################################################################

Started: $(date -Iseconds)

Tests to complete: 42
Tests completed: 0
Tests passing: 0
Tests failing: 0

================================================================================
EOF
        echo -e "${GREEN}Progress file created: $PROGRESS_FILE${NC}"
    fi
}

# Initialize bugs file if it doesn't exist
init_bugs_file() {
    if [ ! -f "$BUGS_FILE" ]; then
        echo -e "${YELLOW}Initializing bugs tracking file...${NC}"
        cat > "$BUGS_FILE" << 'EOF'
# Bugs Found During Exploratory Testing

This file tracks bugs discovered during automated exploratory testing.

## Critical (Blocking)

## High (Should fix before release)

## Medium (Should fix soon after release)

## Low (Nice to fix)

## Polish Items (UX improvements)

---
*Generated by Ralph Wiggum exploratory testing loop*
EOF
        echo -e "${GREEN}Bugs file created: $BUGS_FILE${NC}"
    fi
}

# Count remaining tests
count_remaining_tests() {
    # Count tests where passes is false
    grep -c '"passes": false' "$TESTS_FILE" 2>/dev/null || echo "0"
}

# Get current iteration stats
get_stats() {
    local total=$(grep -c '"id":' "$TESTS_FILE" 2>/dev/null || echo "0")
    local passing=$(grep -c '"passes": true' "$TESTS_FILE" 2>/dev/null || echo "0")
    local remaining=$(count_remaining_tests)
    echo "$total $passing $remaining"
}

# Run single iteration
run_iteration() {
    local iteration=$1
    local remaining=$(count_remaining_tests)

    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  Iteration $iteration of $MAX_ITERATIONS                          ${NC}"
    echo -e "${BLUE}  Tests remaining: $remaining                                      ${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    # Check if all tests are done
    if [ "$remaining" -eq 0 ]; then
        echo -e "${GREEN}All tests have been executed!${NC}"
        return 1
    fi

    # Run Claude Code with the prompt
    # Using --dangerously-skip-permissions for autonomous operation
    # Note: Be careful - this allows file operations without confirmation
    echo -e "${YELLOW}Starting Claude Code iteration...${NC}"

    cd "$PROJECT_DIR"

    # Read the prompt file content
    local prompt_content
    prompt_content=$(cat "$PROMPT_FILE")

    # Run Claude Code in print mode (non-interactive)
    # -p: print mode (non-interactive, outputs to stdout)
    # --dangerously-skip-permissions: allows autonomous file operations
    claude -p --dangerously-skip-permissions "$prompt_content"

    local exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo -e "${YELLOW}Claude Code exited with code: $exit_code${NC}"
    fi

    return 0
}

# Print final summary
print_summary() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                    TESTING COMPLETE                            ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    read -ra stats <<< "$(get_stats)"
    local total=${stats[0]}
    local passing=${stats[1]}
    local remaining=${stats[2]}
    local failed=$((total - passing - remaining))

    echo -e "Total tests:     ${BLUE}$total${NC}"
    echo -e "Passing:         ${GREEN}$passing${NC}"
    echo -e "Failing:         ${RED}$failed${NC}"
    echo -e "Not executed:    ${YELLOW}$remaining${NC}"
    echo ""
    echo -e "Progress file:   ${BLUE}$PROGRESS_FILE${NC}"
    echo -e "Bugs found:      ${BLUE}$BUGS_FILE${NC}"
    echo ""
}

# Main execution
main() {
    echo -e "${YELLOW}Max iterations: $MAX_ITERATIONS${NC}"
    echo ""

    check_prerequisites
    init_progress_file
    init_bugs_file

    local iteration=1

    while [ $iteration -le $MAX_ITERATIONS ]; do
        if ! run_iteration $iteration; then
            break
        fi

        iteration=$((iteration + 1))

        # Small delay between iterations to prevent rate limiting
        sleep 2
    done

    print_summary
}

# Handle Ctrl+C gracefully
trap 'echo -e "\n${YELLOW}Interrupted. Progress saved to $PROGRESS_FILE${NC}"; print_summary; exit 0' INT

# Run main
main
